# -*- coding: utf-8 -*-
"""Existencias equinas - 2008 a 2019

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geYQyO3zSBBUZ8P0ai_vnLAvB2EhAmd8
"""

def crearDFcsv(archivo):
    from os.path import isdir # Esta forma de importar permite llamar en este caso a la función isdir, sin especificar la ruta del módulo del cual proviene.
    from pandas import read_csv
    ruta = "/content/drive/MyDrive/Archivos auxiliares Curso Python/" # Esta variable debe ser editada para que apunte a la ruta donde se guardan los .csv para importar.

    if isdir('/content/drive'):   # Con isdir se comprueba si el directorio del Drive existe, devuelve true o false, es decir si ya está vinculado el Google Drive devuelve true.
      df = read_csv(ruta + archivo + '.csv')
      return df                                #Si G.Drive ya está vinculado, toma el archivo que se le indique por parámetro y crea un Dataframe llamado df, y devuelve el mismo como resultado.

    else:   #Si el Drive no está montado, pasa a montarlo, y con las funciones importadas lo que hace es evitar mostrar el mensaje "mounted to /content/drive" que arroja la función drive.mount al completarse.
      print('Montando Drive...')
      from contextlib import redirect_stdout
      from io import StringIO

      with redirect_stdout(StringIO()):
        from google.colab.drive import mount
        mount('/content/drive')

      df = read_csv(ruta + archivo + '.csv')
      return df

# tablaventas = crearDFcsv('ventas')   # Ejemplo de creación de dataframe llamado "tablaventas" desde un csv almacenado en la carpeta especificada en la variable 'ruta'.

# Tener en cuenta que el argumento que se le pasa a la función (el nombre del archivo sin su extensión) debe estar entre comillas, para que lo tome como texto directamente.

df_caballos = crearDFcsv('ee0819')

import pandas as pd

df_caballos_r = pd.read_csv("/content/drive/MyDrive/Archivos auxiliares Curso Python/ee0819r.csv", encoding = 'latin-1')

df_caballos.info()
df_caballos

df_caballos_r.info()
df_caballos_r

def comparar_campos(df1, df2):
    campos_df1 = tuple(df1.columns)
    campos_df2 = tuple(df2.columns)
    comunes = []
    no_comunes = []

    for i in campos_df1:
        if i in(campos_df2):
          comunes.append(i)
        else:
          no_comunes.append(i)

    for i in campos_df2:
        if i not in(comunes):
          no_comunes.append(i)

    print('Campos comunes:', comunes)
    print('\n')
    print('Campos no comunes:',no_comunes)

comparar_campos(df_caballos, df_caballos_r)

import matplotlib.pyplot as plt

plt.plot(df_caballos['indice_tiempo'], df_caballos['caballos'], color='blue', label='Caballos')
plt.xlabel('Año')
plt.ylabel('Existencias por millón')
plt.title('Existencias de caballos desde 2008 a 2019')
plt.grid()
plt.show()

plt.plot(df_caballos['indice_tiempo'], df_caballos['padrillos'], color='black', label='Padrillos')
plt.xlabel('Año')
plt.ylabel('Existencias')
plt.title('Existencias de padrillos desde 2008 a 2019')
plt.grid()
plt.show()

plt.plot(df_caballos['indice_tiempo'], df_caballos['burros_asnos'], color='orange', label='Burros / Asnos')
plt.xlabel('Año')
plt.ylabel('Existencias')
plt.title('Existencias de burros_asnos desde 2008 a 2019')
plt.grid()
plt.show()

plt.plot(df_caballos['indice_tiempo'], df_caballos['yeguas'], color='pink', label='Yeguas')
plt.xlabel('Año')
plt.ylabel('Existencias por millón')
plt.title('Existencias de yeguas desde 2008 a 2019')
plt.grid()
plt.show()

plt.plot(df_caballos['indice_tiempo'], df_caballos['mulas'], color='red', label='Mulas')
plt.xlabel('Año')
plt.ylabel('Existencias')
plt.title('Existencias de mulas desde 2008 a 2019')
plt.grid()
plt.show()


plt.plot(df_caballos['indice_tiempo'], df_caballos['potrillos_potrillas'], color='green', label='Potrillos/as')
plt.xlabel('Año')
plt.ylabel('Existencias')
plt.title('Existencias de potrillos_potrillas')
plt.grid()
plt.legend(loc='upper right', bbox_to_anchor=(1.4, 1))
plt.show()

# Regiones:
Pampeana = 'Santa Fe', 'Entre Ríos', 'La Pampa', 'Córdoba', 'Buenos Aires'
Cuyo = 'Mendoza', 'San Juan', 'San Luis'
Patagonia = 'Chubut', 'Neuquén',  'Río Negro', 'Santa Cruz', 'Tierra del Fuego'
Noreste = 'Formosa', 'Chaco', 'Corrientes', 'Misiones'
Noroeste = 'Jujuy', 'Salta', 'Tucumán', 'Catamarca', 'La Rioja', 'Santiago del Estero'

df_caballos_r['Region'] = df_caballos_r['provincia'].apply(lambda x: 'Pampeana' if x in(Pampeana) else (
                                                                      'Cuyo' if x in(Cuyo) else (
                                                                        'Patagonia' if x in(Patagonia) else (
                                                                            'Noreste' if x in(Noreste) else (
                                                                                'Noroeste' if x in(Noroeste) else 'Otra')))))

df_caballos_r

import matplotlib.pyplot as plt
import pandas as pd

df_caballos_pampeana = df_caballos_r[df_caballos_r['Region'] == 'Pampeana']
df_caballos_cuyo = df_caballos_r[df_caballos_r['Region'] == 'Cuyo']
df_caballos_patagonia = df_caballos_r[df_caballos_r['Region'] == 'Patagonia']
df_caballos_noroeste = df_caballos_r[df_caballos_r['Region'] == 'Noroeste']
df_caballos_noreste = df_caballos_r[df_caballos_r['Region'] == 'Noreste']

columnas_eliminar = ['provincia', 'provincia_id', 'departamento', 'departamento_id']

df_caballos_pampeana = df_caballos_pampeana.drop(columns = columnas_eliminar)
df_caballos_cuyo = df_caballos_cuyo.drop(columns = columnas_eliminar)
df_caballos_patagonia = df_caballos_patagonia.drop(columns = columnas_eliminar)
df_caballos_noreste = df_caballos_noreste.drop(columns = columnas_eliminar)
df_caballos_noroeste = df_caballos_noroeste.drop(columns = columnas_eliminar)

campos_comunes = ['padrillos', 'caballos', 'yeguas', 'potrillos_potrillas', 'mulas', 'burros_asnos']

df_caballos_pampeana = df_caballos_pampeana.groupby('anio')[campos_comunes].sum()
df_caballos_cuyo = df_caballos_cuyo.groupby('anio')[campos_comunes].sum()
df_caballos_patagonia = df_caballos_patagonia.groupby('anio')[campos_comunes].sum()
df_caballos_noreste = df_caballos_noreste.groupby('anio')[campos_comunes].sum()
df_caballos_noroeste = df_caballos_noroeste.groupby('anio')[campos_comunes].sum()

df_caballos_cuyo.info()
df_caballos_cuyo

plt.plot(df_caballos_noroeste.index, df_caballos_noroeste['mulas'], df_caballos_patagonia['mulas'])
plt.xlabel('Año')
plt.ylabel('Existencias')
plt.title('Existencias de mulas desde 2008 a 2019, por región')

plt.grid()
plt.show()

df_caballos_noreste.



print('Región Noroeste:')
print(df_caballos_noroeste['mulas'])
print('\nRegión Patagonia:')
print(df_caballos_patagonia['mulas'])